# VacationPy
----

#### Note
* Keep an eye on your API usage. Use https://developers.google.com/maps/reporting/gmp-reporting as reference for how to monitor your usage and billing.

* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [4]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os
import json
import time

# Import API key
from api_keys import g_key

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [5]:
# Loading csv output from WeatherPy excercie
weatherdata_df = pd.read_csv("../output_data/cities.csv")
weatherdata_df.head(10)

,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
0,jamestown,42.0970,-79.2353,21.00,73,90,6.91,US,1612075009
1,bambous virieux,-20.3428,57.7575,86.00,66,40,10.36,MU,1612075244
2,vaini,-21.2000,-175.2000,78.80,94,75,5.75,TO,1612075244
3,grindavik,63.8424,-22.4338,21.20,93,90,5.75,IS,1612075244
4,cherskiy,68.7500,161.3000,-35.30,83,0,0.54,RU,1612075020
5,hobart,-42.8794,147.3294,70.00,48,75,11.50,AU,1612074988
6,pokhara,28.2333,83.9833,66.67,26,0,6.91,NP,1612075244
7,laguna,38.4210,-121.4238,50.00,81,75,4.79,US,1612075245
8,saint george,37.1041,-113.5841,37.99,75,1,2.21,US,1612075245
9,bose,45.4612,8.0137,39.99,97,96,2.33,IT,1612075246

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [10]:
# Configure gmaps
gmaps.configure(api_key=g_key)

# Store latitude and longitude lists in variable
locations = weatherdata_df[["Lat", "Lng"]]

# Store humidity list in variable
humidity = weatherdata_df["Humidity"]
intensity = weatherdata_df["Humidity"].max()

In [11]:
# Plot Heatmap
fig_hm = gmaps.figure()

# Create heat layer
heat_layer = gmaps.heatmap_layer(locations, weights=humidity, 
                                 dissipating=False, max_intensity=float(intensity),
                                 point_radius=1)


# Add layer
fig_hm.add_layer(heat_layer)

# Display figure
fig_hm

Figure(layout=FigureLayout(height='420px'))

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [12]:
# Ideal vacation weather conditions: '>80 degrees', 'wind speed 5 or <', 'humidity < 50', 'cloudiness < 30'
conditions = weatherdata_df[(weatherdata_df["Max Temp"] < 80) | (weatherdata_df["Wind Speed"] > 10) | 
                            (weatherdata_df["Humidity"] > 60) | (weatherdata_df["Cloudiness"] > 30)].index

weatherdata_df.drop(conditions, inplace = True)
weatherdata_df

# Save file for future reference
weatherdata_df.to_csv("../output_data/ideal_vac_locs.csv")

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [13]:
# Create list for hotel names to be appended to and specify radius
hotel_names = []
radius = 5000

# Loop through dataframe above to acquire locations
for row in range(len(weatherdata_df)):

    lats = weatherdata_df.iloc[row,1]
    lngs = weatherdata_df.iloc[row,2]
    coords = f"{lats},{lngs}"
    print(coords)

    params = {
        "location": coords,
        "types": "lodging",
        "radius": 5000,
        "key": g_key
    }

    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"   

    response = requests.get(base_url, params=params)
    vacspots_hotel = response.json()


    try:
        hotel_names.append(vacspots_hotel["results"][row]["name"])
    except:
        hotel_names.append("Nearest hotel not found")

print(hotel_names)

15.4992,101.6897
5.4112,100.3354
-33.65,115.3333
-35.1167,147.3667
-37.0667,144.2167
-25.1667,45.05
25.3616,69.7362
15.1167,105.7833
12.9762,77.6033
-7.2,35.7333
23.6333,94.4167
['Jong Jaroen Resort', 'JEN Penang Georgetown by Shangri-La', 'Amalfi Resort Busselton', 'Mercure Wagga Wagga', 'Big4 Castlemaine Gardens Holiday Park', 'Nearest hotel not found', 'Friends hostel', 'Pakse Mekhong Hotel', 'Hotel Bangalore Gate', 'Nearest hotel not found', 'Nearest hotel not found']

In [29]:
# Create dataframe from these locations
weatherdata_df["Hotel Name"] = hotel_names
hotel_df = weatherdata_df
hotel_df["Date"] = pd.to_datetime(hotel_df["Date"])
hotel_df

,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date,Hotel Name
0,bamnet narong,15.4992,101.6897,87.94,32,8,8.84,TH,1970-01-01 00:00:01.612075246,Jong Jaroen Resort
1,georgetown,5.4112,100.3354,89.60,55,20,9.22,MY,1970-01-01 00:00:01.612075241,JEN Penang Georgetown by Shangri-La
2,busselton,-33.6500,115.3333,93.99,28,0,4.00,AU,1970-01-01 00:00:01.612075261,Amalfi Resort Busselton
3,wagga wagga,-35.1167,147.3667,90.00,26,0,9.22,AU,1970-01-01 00:00:01.612075271,Mercure Wagga Wagga
4,castlemaine,-37.0667,144.2167,84.99,27,0,3.00,AU,1970-01-01 00:00:01.612075312,Big4 Castlemaine Gardens Holiday Park
5,beloha,-25.1667,45.0500,92.98,41,0,5.82,MG,1970-01-01 00:00:01.612075324,Nearest hotel not found
6,umarkot,25.3616,69.7362,80.89,15,0,9.33,PK,1970-01-01 00:00:01.612075330,Friends hostel
7,pakxe,15.1167,105.7833,87.80,35,20,2.30,LA,1970-01-01 00:00:01.612075331,Pakse Mekhong Hotel
8,bangalore,12.9762,77.6033,81.00,36,0,6.91,IN,1970-01-01 00:00:01.612075345,Hotel Bangalore Gate
9,izazi,-7.2000,35.7333,81.14,58,18,2.06,TZ,1970-01-01 00:00:01.612075365,Nearest hotel not found
10,mawlaik,23.6333,94.4167,85.75,24,0,1.83,MM,1970-01-01 00:00:01.612075374,Nearest hotel not found

In [30]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
locations = hotel_df[["Lat", "Lng"]]

In [31]:
# Add marker layer ontop of heat map
marker_locations = locations

# fig = gmaps.figure()
markers = gmaps.marker_layer(marker_locations,info_box_content = hotel_info)
fig_hm.add_layer(markers)

# Display figure
fig_hm

Figure(layout=FigureLayout(height='420px'))